name: Build OxCaml LLVM

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   arch: x86_64
          #   artifact_name: llvm-linux-x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
            artifact_name: llvm-linux-aarch64
          # - os: macos-latest
          #   arch: arm64
          #   artifact_name: llvm-macos-arm64
    permissions: {}
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build python3 build-essential clang

    - name: Build LLVM
      env:
        CC: clang
        CXX: clang++
      run: |
        mkdir build
        cd build
        cmake -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DLLVM_ENABLE_PROJECTS="clang;lldb" \
              -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind" \
              -DLLVM_TARGETS_TO_BUILD="X86;AArch64" \
              ../llvm
        ninja lldb

    - name: Test LLDB
      env:
        CC: clang
        CXX: clang++
      run: |
        cd build
        ninja check-lldb
